version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build CSFundamentalAlgorithms.sln
      - run:
          name: tests
          command: dotnet test CSFundamentalAlgorithmsTests/CSFundamentalAlgorithmsTests.csproj
